exports.POEMS = [
  {
    id: "the-bridge-that-broke-her-love",
    title: "The Bridge That Broke Her Love",
    lines: [
      "What it is? OR",
      "What we had? OR",
      "What was between us?",
      "kabhi koi aaye apna bnaye",
      "or ek din bas chala jaye",
      "socha hai kaisa lgta hai?",
      "'LOVE' what we used to call it",
      "hann ki hai kai dafa mohabbat usse",
      "uski nazron se",
      "uski baaton se",
      "uski yaadon se",
      "Then why it ended?",
      "Wasn't 'Love' beautiful?",
      "hann khwaab jaisi h yeh mohabbat",
      "jiska ankh khulte hi thikana ni.",
    ],
  },
  {
    id: "was-that-love",
    title: "Was That Love?",
    lines: [
      "And the world goes on",
      "Time between us flied away",
      "A long time back you chose to walk alone,",
      "Or I will say just leaving me behind",
      "A time, with lots of promises",
      "Promises to be together",
      "Together fighting everything",
      "But soon you realise, I was a time waste",
      "Time waste, ohhh! After all these months",
      "Months of happy moments",
      "Moments that made me fall for you",
      "You, gone! To have your peace",
      "Peace is what I don't have anymore",
      "Things! No, I just lost myself",
      "Self that only wants us",
      "Us! For you, there is no we",
      "We laughed together,",
      "But you made me cry all alone",
      "Move on! People say",
      "But can you tell me how!?",
      "The more I try to stay away from you",
      "The more it hurts",
      "The more it gets worse",
      "Me thinking why don't you come back",
      "Am I that bad",
      "Or it was just a dream",
      "A dream that’s never gonna get fulfilled",
      "You think I am mad",
      "Yes, madness is all that is left inside me",
      "A happy girl — all she tries to do now is fake happiness",
      "Cause of pain...",
      "Oh no, now she doesn’t feel it anymore",
      "All she desires now is herself",
      "Her identity that is so lost in loving you",
      "That she forgets to love herself",
      "The bridge you made between you and her",
      "All she is trying to do is run away from it now",
      "Because",
      "She had lost everything in order to cross that bridge",
      "And now...",
      "Now she is no more left — even to get that peace which she desired...",
    ],
  },
  {
    id: "was-it-us",
    title: "Was it US?",
    lines: [
      "Was it you",
      "Was it me",
      "Was it lie",
      "Was it true",
      "Was it funny",
      "Was it tears",
      "Was it a puzzle",
      "Was it a solution",
      "Was it i want",
      "Was it you wanted",
      "Was it craving",
      "Was it desire",
      "Was it reality",
      "Was it dream",
      "Was it destiny",
      "Or it was our FATE",
    ],
  },
  {
    id: "before-i-break-again",
    title: "Before I Break Again",
    lines: [
      "Being good is what I don't want to be now",
      "Being weak is what I hate to be now",
      "The tears in my eyes",
      "The pain in my heart",
      "The questions in my mind",
      "Me, myself, judging my thoughts",
      "Getting tired by these emotions",
      "Getting lost in my sorrows",
      "Pulling myself back",
      "Getting stuck",
      "Feeling heavy",
      "The fear of failing again",
      "Driving me crazy",
      "I know it’s not the start",
      "But I feel like it is ending",
      "The emotions too heavy to carry",
      "Me feeling graved in them",
      "Dying to hear the right words",
      "But doing the wrong things",
      "Becoming heartless with all the feelings",
      "Is what I think is called death",
      "Before losing the breath",
    ],
  },
  {
    id: "will-i-ever-escape-it",
    title: "Will I Ever Escape It?",
    lines: [
      "The fear of falling apart",
      "The crime of being innocent",
      "The jury for all your doings",
      "Will i ever escape it?",
      "The point of not telling",
      "The part not being fixed",
      "The place that isolates",
      "Will i ever escape it?",
      "The shivering of my hands",
      "The crumbeled words",
      "The faith i broke",
      "Will i ever escape it?",
      "The burden i became",
      "The reason i was born",
      "The shattered world",
      "Will i ever escape it?",
      "The unreal me",
      "The terrible me",
      "The act of i don't care me",
      "Will i ever stop it?",
      "When will i escape it???",
      "When will i escape it???",
    ],
  },
  {
    id: "i-like-to-be",
    title: "I Like to Be...",
    lines: [
      "I like to be summoned",
      "I like to be called",
      "I like to be filled",
      "I like to be talked",
      "I like to be happy",
      "I like to be dancing",
      "I like to be prayed",
      "I like to be heard",
      "I like to be charished",
      "I like to be cared",
      "I like to be missed",
      "I love to be loved..",
    ],
  },
  {
    id: "filling-the-void",
    title: "Filling the Void",
    lines: [
      "Does it wonder you too",
      "How foolish we act",
      "Out of no trace",
      "We just do what we wished for",
      "But does it worth",
      "Chasing the unknown",
      "Driving crazy something",
      "That can never be yours",
      "Leaving yourself behind",
      "To get close to it",
      "We like to be filled",
      "But have we wondered what we are filling in.",
    ],
  },
  {
    id: "will-you-be-mine",
    title: "Will You Be Mine?",
    lines: [
      "In these silent nights,",
      "Me afraid of sleeping light,",
      "You told me it's all right,",
      "Just close your eyes,",
      "Think bright,",
      "Be with me, I will be fine,",
      "The songs rhyme,",
      "These lines,",
      "Me trying to tell you,",
      "That you are mine,",
      "Fear of hurting you might,",
      "Hold me back,",
      "To say things that you deserve to listen right,",
      "I think with passing time things would change for better kind,",
      "I will be yours, you will be mine...",
      "Maybe at end things would be all right.",
      "Can you hold my hand tight...",
      "Be with me on my side,",
      "I don't know about future,",
      "Because it's not at all justified,",
      "But I know I want to be your present and you my future at",
      "This point of my time,",
      "You make me laugh, you make me smile, you made me",
      "wonder it's all in my mind...",
      "Can I ask you, will you be mine?",
      "I will be yours,",
      "You will be mine...",
      "I think if we are in this together, things would work fine...",
    ],
  },
  {
    id: "what-i-crave",
    title: "What I Crave",
    lines: [
      "What I crave is",
      "Love? Do I",
      "But do I deserve it",
      "Or will I get it.",
      "The silence it's peaceful",
      "when you are with me.",
      "I think",
      "What I crave right now",
      "Is.....",
      "Your eyes, your lips, your touch",
      "May be it's not feelings",
      "May be it just us",
      "The two threads getting knot",
      "together unknowingly.",
    ],
  },
  {
    id: "yes-i-am-immature",
    title: "Yes, I Am Immature",
    lines: [
      "They call me immature",
      "Am I?",
      "If laughing in pain is being immature",
      "then i am.",
      "If texting people on time is being callow",
      "then i am.",
      "If getting attached is being stupid",
      "then i am.",
      "If not crying over my broken dreams is being coward",
      "then i am.",
      "If being yourself is being unsophisticated",
      "then i am.",
      "If missing people who are no more is being babyish",
      "then i am.",
      "If not keeping attitude all the time is being childish",
      "then i am.",
      "If consoling people in their problems is being crude",
      "then i am.",
      "If I being IMPERFECT is being IMMATURE for you",
      "then Yes!",
      "I am immature....",
    ],
  },
  {
    id: "do-you-know-who-i-am",
    title: "Do You Know Who I Am?",
    lines: [
      "Do you know who i am???",
      "I guess you're not",
      "The girl of your dreams.",
      "Ohh never, I don’t want to",
      "Be anyone's dream girl —",
      "I want to be me.",
      "I am kind, I am strong,",
      "I like it — but if it’s not wrong...",
      "I know you think you",
      "Know me, but do you?",
      "Everyone has different",
      "Shades — so do I.",
      "The deeper you go, the",
      "Darker you find.",
      "Is it good to be stuck in",
      "The past? I think not,",
      "It’s not healthy.",
      "That’s why I am not",
      "Getting well.",
      "I think...",
      "I love hard — that it",
      "Suffocates me only.",
      "I hate hard — that it makes",
      "You dead for me.",
      "I know I am not good,",
      "But what’s the fun in",
      "Being so great",
      "When you can be yourself",
      "Rather than being a",
      'Perfect "something else."',
      "ome people think I write",
      "Because of them —",
      "I think you should think again.",
      "Do you know me?",
      "Just a piece of a paragraph makes",
      "Me feel worth it.",
      "And I lose my worth",
      "Due to some words.",
      "Is it okay to myself?",
      "Is it really fair to myself?",
      "Why do I try to find peace in",
      "Others?",
      "Why do I need other",
      "People to tell me my",
      "Worth?",
      "Aren’t we enough for",
      "Ourselves?",
      "Why do I keep searching",
      "In the dark",
      "When I, myself, am the light?",
      "It’s not about me — I think",
      "We all should ask:",
      "Do we know us?",
      "Or do we just",
      "Know what others",
      "Have told us...?",
    ],
  },
  {
    id: "the-pain-he-left-behind",
    title: "The pain he left behind.",
    lines: [
      "My eyes in tears,",
      "My heart in pain,",
      "The guilt of loss,",
      "The pain of not saving him,",
      "The destroyed world.",
      "The loneliness, the empty world,",
      "The freakin' mind, the numb body,",
      "The clueless thoughts, the infinite tears,",
      "The grief of losing, the peace shattering.",
      "Heart aching, the voice choking,",
      "The light breaking, the night darkening,",
      "The words pinching.",
      "The house so lone, the place — no love,",
      "The question he left, the smile he brought,",
      "My joy he was, the happiness he gave,",
      "The love I do.",
      "The voiceless conversations I have with him,",
      "The peace he gave me, the pain he left.",
      "The things are messed,",
      "My life is tested.",
    ],
  },
  {
    id: "if-words-could-hit-me-1",
    title: "If words could hit me....",
    lines: ["I found peace in you", "but you left me with nothing."],
  },
  {
    id: "if-words-could-hit-me-2",
    title: "If words could hit me....",
    lines: [
      "At the end, we realize that we are no longer afraid of the future,",
      "we were just regretting our past.",
    ],
  },
  {
    id: "if-words-could-hit-me-3",
    title: "If words could hit me....",
    lines: [
      "If we ever cross paths",
      "Will you dare to look into my eyes?",
      "Coz,",
      "Maybe they are in still in search of you.",
    ],
  },
  {
    id: "if-words-could-hit-me-4",
    title: "If words could hit me....",
    lines: ["I don't write coz of a heartbreak", "I write coz these words never leave me...."],
  },
  {
    id: "if-words-could-hit-me-5",
    title: "If words could hit me....",
    lines: ["If there was a time when you loved me", "Then I think its my right to know why?"],
  },
  {
    id: "if-words-could-hit-me-6",
    title: "If words could hit me....",
    lines: ["If timing was wrong then why it happened?"],
  },
  {
    id: "if-words-could-hit-me-7",
    title: "If words could hit me....",
    lines: ["May be you are the right person", "But our timing is wrong."],
  },
  {
    id: "if-words-could-hit-me-8",
    title: "If words could hit me....",
    lines: ["I wanted you to read my eyes", "Not what I say on text."],
  },
  {
    id: "if-words-could-hit-me-9",
    title: "If words could hit me....",
    lines: ["I waited...", "I waited to See", "How hard your words will hurt me"],
  },
]